#!/bin/zsh
DIR=$(pwd)
source run-env
rm -rf $DIR/dist
mkdir $DIR/dist
pip freeze > $DIR/requirements.txt
pip install --target $DIR/dist -r $DIR/requirements.txt
cp -rf $DIR/*.py $DIR/dist
cd $DIR/dist
zip -r $DIR/function.zip .
cd $DIR