#!/bin/zsh
DIR=$(pwd)
virtualenv $DIR/virtualenv
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
echo "To quit the virtualenv type 'deactivate'"
source $DIR/virtualenv/bin/activate
echo $(which python)